# Generated by Django 4.0.4 on 2022-04-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mebel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(db_index=True, max_length=250)),
                ('Info', models.TextField(db_index=True, max_length=10000)),
                ('Malumot', models.TextField(db_index=True, max_length=10000)),
                ('image', models.ImageField(blank=True, db_index=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
