# Generated by Django 4.0.4 on 2022-04-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_customuser_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ism', models.CharField(db_index=True, max_length=250)),
                ('Tel', models.TextField(db_index=True, max_length=10000)),
                ('Pochta', models.TextField(db_index=True, max_length=10000)),
                ('Xabar', models.TextField(db_index=True, max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
